# Generated by Django 5.0 on 2023-12-11 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='preview',
            field=models.ImageField(blank=True, upload_to='uploads/previews/'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='No description')),
                ('price', models.FloatField(blank=True, default=0)),
                ('wiki_link', models.TextField(blank=True, default='No wiki link')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.category')),
            ],
        ),
    ]
