# Generated by Django 5.0 on 2023-12-25 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'active'), (1, 'finished'), (2, 'canceled')], default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('finish_date', models.DateTimeField(blank=True)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.category')),
                ('products', models.ManyToManyField(blank=True, related_name='orders', to='app.productstack')),
            ],
        ),
    ]
