# Generated by Django 5.0 on 2023-12-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finish_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
