# Generated by Django 5.0 on 2023-12-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
